AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'bin/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'

Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Lint/UnreachableCode:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Metrics/BlockLength:
  Max: 25
Style/FrozenStringLiteralComment:
  Enabled: false
